version: "3.8"
services:
  redis:
    image: "redis"
  mongodb:
    image: "mongo"
    ports:
      - "27018:27017"
  node-app:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - /usr/app/node_modules
      - .:/usr/app
